### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by nickky92** [dantudose/SM-PWM-01A#1]
In the datasheet it is specified that the output is in pcs/ft^3 but you mention that the output is in ug/m^3,  ug-implies that you know the mass of a particle, I strongly belive that the output is in pcs/ft^3 as in the datasheet, is that correct, note that this method of detecting is optical and detects particle based on the size not their mass.

**Comment by dantudose** [comment]
True, the information is scant. The datasheet covers only a part of it and I had to piece out other hints from a few code examples that I found online. Try this too: https://github.com/ductsoup/Air-Quality-Sensor-Suite
